// AUTO-GENERATED by the fish-image fetch pipeline — do not edit by hand.
// Bundled 500px Wikimedia Commons thumbnails plus per-photo attribution,
// keyed by fish id. Regenerate by re-running the fetch + apply scripts.
//
// FISH_THUMBS: offline-first thumbnails (lists use these directly; the detail
// gallery layers the remote hi-res from fish.json `images` on top).
// FISH_IMAGE_CREDITS: artist + license for the in-app credit line; full
// source links live in CREDITS.md.

export const FISH_THUMBS: Record<string, number> = {};

export const FISH_IMAGE_CREDITS: Record<
  string,
  { artist: string; license: string }
> = {};
