// AUTO-GENERATED by the plant-image fetch pipeline — do not edit by hand.
// Bundled 500px Wikimedia Commons thumbnails plus per-photo attribution,
// keyed by plant id. Cultivars and trade forms of the same species share one
// photo (and one bundled file). Regenerate via the fetch + apply scripts.

export const PLANT_THUMBS: Record<string, number> = {};

export const PLANT_IMAGE_CREDITS: Record<
  string,
  { artist: string; license: string }
> = {};
